export const HE = {
  APP_NAME: 'אורייתא',
  APP_SUBTITLE: 'מערכת לניהול, לימוד ותרגול מקורות יהודיים',

  NAV_ADD: 'הוסף ציטוט',
  NAV_STUDY: 'לימוד',
  NAV_QUIZ: 'חידון',
  NAV_ABOUT: 'אודות',
  NAV_LOGOUT: 'יציאה',
  NAV_TALMUD: 'תלמוד',
  NAV_RABBIS: 'רבנים',
  NAV_GEMATRIA: 'גימטריות',
  NAV_LEARN: 'תרגול',
  TALMUD_TAB_VIEW: 'צפייה',
  TALMUD_TAB_ADD: 'הוספה',
  RABBIS_TITLE: 'רבנים',
  RABBIS_SUBTITLE: 'מנהיגים ופוסקים לדורותיהם',
  RABBIS_SEARCH_PLACEHOLDER: 'חיפוש לפי שם, כינוי או תיאור...',
  RABBIS_FILTER_ALL: 'הכל',
  RABBI_ADD_BTN: 'הוסף רב',
  RABBI_FORM_EDIT_TITLE: 'עריכת רב',
  RABBI_FORM_ADD_TITLE: 'הוסף רב חדש',
  RABBI_FORM_NAME: 'שם',
  RABBI_FORM_FULL_NAME: 'שם מלא (אופציונלי)',
  RABBI_FORM_CATEGORY: 'קטגוריה',
  RABBI_FORM_SORT_YEAR: 'שנת מיון',
  RABBI_FORM_DATE_PERIOD: 'תקופה (תצוגה)',
  RABBI_FORM_IS_ALIVE: 'עדיין בחיים',
  RABBI_FORM_BIO: 'תיאור',
  RABBI_FORM_SAVE: 'שמור',
  RABBI_DELETE_CONFIRM: 'האם למחוק את הרב מהמאגר?',
  RABBI_DELETE_SUCCESS: 'הרב נמחק',
  RABBI_SAVE_SUCCESS: 'הרב נשמר בהצלחה',
  RABBI_SAVE_ERROR: 'שגיאה בשמירה, נסה שנית',
  RABBIS_COUNT: (n: number) => `· ${n} רבנים`,

  GEMATRIA_TITLE: 'גימטריות',
  GEMATRIA_SUBTITLE: 'חישוב ערכי אותיות במילים ושמות',
  GEMATRIA_SEARCH_PLACEHOLDER: 'חיפוש לפי מילה או ערך...',
  GEMATRIA_ADD_BTN: 'הוסף גימטריה',
  GEMATRIA_FORM_ADD_TITLE: 'הוסף גימטריה חדשה',
  GEMATRIA_FORM_EDIT_TITLE: 'עריכת גימטריה',
  GEMATRIA_FORM_WORD: 'מילה',
  GEMATRIA_FORM_WORD_PLACEHOLDER: 'למשל: חי',
  GEMATRIA_FORM_VALUE: 'ערך גימטרי (מחושב אוטומטית)',
  GEMATRIA_FORM_SAVE: 'שמור',
  GEMATRIA_DELETE_CONFIRM: 'האם למחוק את הגימטריה מהמאגר?',
  GEMATRIA_SAVE_ERROR: 'שגיאה בשמירה, נסה שנית',
  GEMATRIA_EMPTY: 'לא נמצאו גימטריות',
  GEMATRIA_COUNT: (n: number) => `· ${n} גימטריות`,
  GEMATRIA_VALUE_LABEL: 'ערך',
  DUPLICATE_GEMATRIA: 'מילה זו כבר קיימת במאגר',

  LOGIN_TITLE: 'ברוך הבא לאורייתא',
  LOGIN_SUBTITLE: 'הזן קוד כניסה',
  LOGIN_PLACEHOLDER: 'קוד כניסה',
  LOGIN_BUTTON: 'כניסה',
  LOGIN_ERROR: 'קוד שגוי, נסה שנית',

  ADD_TITLE: 'הוספת ציטוט חדש',
  ADD_CONTENT_LABEL: 'תוכן הציטוט',
  ADD_CONTENT_PLACEHOLDER: 'הזן את תוכן הציטוט...',
  ADD_MASECHET_LABEL: 'מסכת',
  ADD_MASECHET_PLACEHOLDER: 'בחר מסכת',
  ADD_DAF_LABEL: 'דף',
  ADD_DAF_PLACEHOLDER: 'למשל: ד, כ״א',
  ADD_AMUD_LABEL: 'עמוד (אופציונלי)',
  ADD_AMUD_A: 'א',
  ADD_AMUD_B: 'ב',
  ADD_AMUD_NONE: 'ללא',
  ADD_LOCATION_TITLE: 'מיקום',
  ADD_LOCATION_BUTTON: 'הוסף מיקום נוסף',
  ADD_REMOVE_LOCATION: 'הסר מיקום',
  ADD_SUBMIT: 'שמור ציטוט',
  ADD_SUCCESS: 'הציטוט נשמר בהצלחה',
  ADD_ERROR: 'שגיאה בשמירת הציטוט',

  EDIT_TITLE: 'עריכת ציטוט',
  EDIT_SUBMIT: 'שמור שינויים',
  EDIT_SUCCESS: 'הציטוט עודכן בהצלחה',

  DELETE_CONFIRM: 'האם אתה בטוח שברצונך למחוק ציטוט זה?',
  DELETE_SUCCESS: 'הציטוט נמחק',

  STUDY_TITLE: 'לימוד וחזרה',
  STUDY_RANDOM_BUTTON: 'ציטוט אקראי',
  STUDY_RANDOM_TITLE: 'ציטוט אקראי',
  STUDY_RANDOM_NEXT: 'הבא',
  STUDY_FILTER_TITLE: 'סינון',
  STUDY_FILTER_ALL: 'הכל',
  STUDY_FILTER_SEDER: 'סדר',
  STUDY_FILTER_MASECHET: 'מסכת',
  STUDY_SEARCH_PLACEHOLDER: 'חיפוש בציטוטים...',
  STUDY_EMPTY: 'לא נמצאו ציטוטים',
  STUDY_COUNT: (n: number) => `${n} ציטוטים`,
  STUDY_DAF: 'דף',
  STUDY_AMUD: 'עמוד',
  STUDY_EDIT: 'עריכה',
  STUDY_DELETE: 'מחיקה',

  QUIZ_TITLE: 'חידון',
  QUIZ_FILTER_TITLE: 'סנן לפי',
  QUIZ_FILTER_ALL: 'כל הציטוטים',
  QUIZ_NO_RESULTS: 'אין ציטוטים בסינון זה',
  QUIZ_QUESTION: 'זהה את המקור',
  QUIZ_SELECT_MASECHET: 'בחר מסכת',
  QUIZ_ENTER_DAF: 'הזן דף',
  QUIZ_AMUD_OPTIONAL: 'עמוד (אופציונלי)',
  QUIZ_SUBMIT: 'בדוק תשובה',
  QUIZ_NEXT: 'שאלה הבאה',
  QUIZ_CORRECT: 'מושלם!',
  QUIZ_HALF: 'חצי נכון',
  QUIZ_WRONG: 'לא נכון',
  QUIZ_ANSWER_WAS: 'התשובה הנכונה:',
  QUIZ_HINT_BUTTON: 'קבל רמז',
  QUIZ_HINT_LABEL: 'רמז — הסדר:',
  QUIZ_STATS_TITLE: 'סטטיסטיקות',
  QUIZ_ACCURACY: 'דיוק',
  QUIZ_TOTAL: 'סה״כ שאלות',
  QUIZ_TOTAL_SCORE: 'סה״כ ניקוד',
  QUIZ_HISTORY: 'היסטוריה אחרונה',
  QUIZ_SKIP: 'דלג',
  QUIZ_RESET_STATS: 'איפוס סטטיסטיקות',
  QUIZ_RESET_CONFIRM: 'לאפס את כל הסטטיסטיקות?',
  QUIZ_STATS_EMPTY: 'עדיין אין נתונים',
  QUIZ_MODE_CLASSIC: 'חידון קלאסי',
  QUIZ_MODE_MULTIPLE: 'חידון אמריקאי',
  QUIZ_MC_CHOOSE: 'בחר את המקור הנכון',
  QUIZ_MC_NOT_ENOUGH: 'אין מספיק ציטוטים לחידון האמריקאי',
  QUIZ_MODE_COMPLETION: 'השלמת ציטוט',
  QUIZ_MODE_RABBI: 'ניחוש רב',
  QUIZ_RABBI_QUESTION: 'לאיזו קטגוריה שייך הרב?',
  QUIZ_RABBI_NOT_ENOUGH: 'אין רבנים במאגר',
  QUIZ_COMPLETION_PROMPT: 'המשך את הציטוט',
  QUIZ_COMPLETION_PLACEHOLDER: 'הזן את המשך הציטוט...',
  QUIZ_COMPLETION_SUBMIT: 'בדוק',
  QUIZ_COMPLETION_FULL: 'הציטוט המלא:',
  QUIZ_COMPLETION_SOURCE: 'מקור:',
  QUIZ_MODE_GEMATRIA: 'גימטריה',
  QUIZ_GEMATRIA_QUESTION: 'איזו מילה שווה בגימטריה למספר הזה?',
  QUIZ_GEMATRIA_PLACEHOLDER: 'הזן מילה...',
  QUIZ_GEMATRIA_SUBMIT: 'בדוק',
  QUIZ_GEMATRIA_NOT_ENOUGH: 'אין מספיק גימטריות במאגר',
  QUIZ_GEMATRIA_HINT_LABEL: 'רמז — האות הראשונה:',
  QUIZ_GEMATRIA_ANSWERS: 'תשובות אפשריות:',

  ABOUT_TITLE: 'אודות המערכת',
  ABOUT_CREATOR_SECTION: 'יוצר',
  ABOUT_CREATOR_NAME: 'אוראל קקון',
  ABOUT_CREATOR_INITIALS: 'א.ק',
  ABOUT_CREATOR_ROLE: 'פיתוח ועיצוב',
  ABOUT_CREATOR_EMAIL: 'orelkakonweb@gmail.com',
  ABOUT_VERSE: 'לקח טוב נתתי לכם, תורתי אל תעזובו',
  ABOUT_FOOTER: '© 2026 אוראל קקון · אורייתא',
  ABOUT_FEATURES: [
    { icon: '📜', text: 'תלמוד — צפייה, חיפוש ופילטור ציטוטים מהתלמוד הבבלי לפי מסכת, דף ועמוד. ציטוט יכול להופיע במספר מקומות במקביל' },
    { icon: '👥', text: 'רבנים — מאגר כרונולוגי של מאות דמויות יהודיות מהתנ״ך ועד ימינו: תורה, שופטים, מלכים, נביאים, כתובים, זוגות, תנאים, אמוראים, גאונים, ראשונים, אחרונים, חסידים ועוד' },
    { icon: '🔢', text: 'גימטריות — מאגר מילים ושמות עם הערך הגימטרי שלהם (לפי מספר הכרחי), עם חיפוש והוספה/עריכה (הרשאות מנהל)' },
    { icon: '🎓', text: 'תרגול — חמישה מצבי חידון: קלאסי (זהה מסכת ודף), אמריקאי (בחירה מרובה), השלמת ציטוט, ניחוש קטגוריית רב וגימטריה (כתיבת מילה שמתאימה לערך). כולל מערכת רמזים, תצוגת מקור ומעקב ניקוד' },
    { icon: '🗓️', text: 'לוח יומי — זמני תפילה (נץ, שקיעה, צאת הכוכבים ועוד), מצפן לירושלים, דף יומי בבלי וירושלמי, רמב״ם יומי ואירועי לוח השנה העברי' },
    { icon: '✏️', text: 'הוספה, עריכה ומחיקה של ציטוטים, רבנים וגימטריות (הרשאות מנהל בלבד) עם זיהוי אוטומטי של כפילויות לפני שמירה' },
    { icon: '📊', text: 'סטטיסטיקות אישיות — ניקוד ודיוק מצטבר נשמר בכל מכשיר בנפרד, עם היסטוריה של 5 שאלות אחרונות ואפשרות איפוס' },
    { icon: '🌙', text: 'מצב לילה ומצב יום — החלפה בלחיצה, העדפה נשמרת במכשיר' },
    { icon: '📱', text: 'ממשק מותאם מלא למובייל ולמחשב, RTL עברי מלא, נגיש מכל מקום' },
  ],

  THEME_DARK: 'מצב לילה',
  THEME_LIGHT: 'מצב יום',

  DUPLICATE_CITATION_TITLE: 'ציטוט זה כבר קיים במאגר',
  DUPLICATE_CITATION_FOUND_AT: 'נמצא ב:',
  DUPLICATE_CITATION_DISMISS: 'הבנתי',
  DUPLICATE_RABBI: 'רב בשם זה כבר קיים במאגר',

  NAV_TODAY: 'יומי',
  TODAY_TITLE: 'לוח יומי',
  TODAY_SUBTITLE: 'זמנים, לימוד ואירועי היום',
  TODAY_LOCATION_REQUEST: 'אפשר גישה למיקום לקבלת זמני יום מדויקים',
  TODAY_LOCATION_BTN: 'אפשר מיקום',
  TODAY_LOCATION_DENIED: 'גישה למיקום נדחתה',
  TODAY_LOCATION_DENIED_HELP: 'לאישור מחדש: הגדרות הדפדפן ← פרטיות ← מיקום',
  TODAY_LOCATION_RETRY: 'נסה שוב',
  TODAY_ZMANIM_TITLE: 'זמני היום',
  TODAY_ALOT: 'עלות השחר',
  TODAY_SUNRISE: 'הנץ החמה',
  TODAY_SHMA: 'סוף ק״ש (מג״א)',
  TODAY_TFILLA: 'סוף תפילה (מג״א)',
  TODAY_CHATZOT: 'חצות היום',
  TODAY_MINCHA_GEDOLA: 'מנחה גדולה',
  TODAY_PLAG: 'פלג המנחה',
  TODAY_SUNSET: 'שקיעת החמה',
  TODAY_TZEIT: 'צאת הכוכבים',
  TODAY_COMPASS_TITLE: 'כיוון לירושלים',
  TODAY_COMPASS_BEARING: (deg: number) => `${Math.round(deg)}° מצפון`,
  TODAY_COMPASS_DISTANCE: (km: number) => `${km.toLocaleString('he-IL')} ק״מ`,
  TODAY_COMPASS_PERMISSION: 'אפשר מצפן',
  TODAY_DAF_TITLE: 'לימוד יומי',
  TODAY_DAF_BAVLI: 'דף יומי בבלי',
  TODAY_DAF_YERUSHALMI: 'ירושלמי יומי',
  TODAY_DAF_RAMBAM: 'רמב״ם יומי',
  TODAY_PARASHA: 'פרשת השבוע',
  TODAY_EVENTS_TITLE: 'אירועי היום',
  TODAY_EVENTS_EMPTY: 'אין אירועים מיוחדים היום',
  TODAY_ERROR: 'שגיאה בטעינת הנתונים',

  SEDER_ZERAIM: 'סדר זרעים',
  SEDER_MOED: 'סדר מועד',
  SEDER_NASHIM: 'סדר נשים',
  SEDER_NEZIKIN: 'סדר נזיקין',
  SEDER_KODASHIM: 'סדר קדשים',
  SEDER_TAHAROT: 'סדר טהרות',

  ERROR_REQUIRED: 'שדה זה חובה',
  LOADING: 'טוען...',
  SAVE: 'שמור',
  CANCEL: 'ביטול',
  CLOSE: 'סגור',
};
